apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-kube-autoscaler
  annotations:
    team: cicd
  label:
    appType: tradeshift-component
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-kube
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
