apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secret
  labels:
    appType: tradeshift-component
  annotations:
    team: dev-prod
type: Opaque
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
