kind: Service
apiVersion: v1
metadata:
  # DNS name to give the service
  name: hello-kube
  labels:
    appType: tradeshift-component
  annotations:
    team: dev-prod
    consul.sync: tradeshift-db
spec:
  # This selector will include all pods that matches the criteria below.
  # the will search for all pods with metadata containing 'app: hello'
  type: NodePort
  selector:
    app: hello-kube
  ports:
    - protocol: TCP
      # Expose port 8080 to other service in the cluster, they can now
      # access it via http://hello:8080
      port: 8080
